name: API Test & Xray Publish

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running the manual API test'
        required: false
        default: 'Manual trigger from GitHub UI'

jobs:
  test_and_report:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Repository
        uses: actions/checkout@v4

      # - name: ğŸ› ï¸ Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'

      # - name: â¬‡ï¸ Install pnpm globally
      #   run: npm install -g pnpm

      # - name: ğŸ“¦ Install dependencies
      #   run: pnpm install

      # - name: ğŸ§ª Run TypeScript Tests and Generate JUnit Report
      #   run: pnpm test
      #   continue-on-error: true

      - name: ğŸ’¾ Upload Test Report Artifact (Optional)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit-test-report
          path: ./test-results/junit-report.xml
          
      - name: ğŸ•µï¸ List test-results directory
        run: ls -la ./test-results
        if: always()
      - name: ğŸ“„ Show JUnit XML
        run: cat ./test-results/junit-report.xml
        if: always()

      # https://github.com/mikepenz/xray-action
      - name: â« Publish Results to Jira Xray
        uses: mikepenz/xray-action@v3
        if: always()
        with:
          username: ${{ secrets.XRAY_CLIENT_ID }}
          password: ${{ secrets.XRAY_CLIENT_SECRET }}
          testFormat: "junit"
          testPaths: "./test-results/junit-report.xml"
          testExecKey: "TSE-10"
          xrayCloud: "false"
          xrayBaseUrl: ${{ secrets.JIRA_BASE_URL }}
          importParallelism: 1
          importRetryLimit: 1
          responseTimeout: 10000