name: API Test & Xray Publish

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running the manual API test'
        required: false
        default: 'Manual trigger from GitHub UI'

jobs:
  test_and_report:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm' 
          cache-dependency-path: 'pnpm-lock.yaml' 

      - name: â¬‡ï¸ Install pnpm globally
        run: npm install -g pnpm

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸ’¾ Upload Test Report Artifact (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-report
          path: ./test-results/junit-report.xml
          
      # https://github.com/mikepenz/xray-action
      - name: â« Publish Results to Jira Xray
        uses: mikepenz/xray-action@v1
        with:
          username: ${{ secrets.XRAY_CLIENT_ID }}
          password: ${{ secrets.XRAY_CLIENT_SECRET }}
          testFormat: "junit"
          testPaths: "./test-results/junit-report.xml"
          testExecKey: "TSE-10"
          xrayCloud: "false"